// Code generated by protoc-gen-go. DO NOT EDIT.
// source: processor_nhan_vien.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NhanVien struct {
	DmNhanVienId         uint32   `protobuf:"varint,1,opt,name=dm_nhan_vien_id,json=dmNhanVienId,proto3" json:"dm_nhan_vien_id,omitempty"`
	MaNhanVien           string   `protobuf:"bytes,2,opt,name=ma_nhan_vien,json=maNhanVien,proto3" json:"ma_nhan_vien,omitempty"`
	TenNhanVien          string   `protobuf:"bytes,3,opt,name=ten_nhan_vien,json=tenNhanVien,proto3" json:"ten_nhan_vien,omitempty"`
	FullName             string   `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhongId              uint32   `protobuf:"varint,6,opt,name=phong_id,json=phongId,proto3" json:"phong_id,omitempty"`
	DmChucDanhId         uint32   `protobuf:"varint,7,opt,name=dm_chuc_danh_id,json=dmChucDanhId,proto3" json:"dm_chuc_danh_id,omitempty"`
	DmChucVuId           uint32   `protobuf:"varint,8,opt,name=dm_chuc_vu_id,json=dmChucVuId,proto3" json:"dm_chuc_vu_id,omitempty"`
	SoDienThoai          string   `protobuf:"bytes,9,opt,name=so_dien_thoai,json=soDienThoai,proto3" json:"so_dien_thoai,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NhanVien) Reset()         { *m = NhanVien{} }
func (m *NhanVien) String() string { return proto.CompactTextString(m) }
func (*NhanVien) ProtoMessage()    {}
func (*NhanVien) Descriptor() ([]byte, []int) {
	return fileDescriptor_c946787ad119af67, []int{0}
}

func (m *NhanVien) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NhanVien.Unmarshal(m, b)
}
func (m *NhanVien) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NhanVien.Marshal(b, m, deterministic)
}
func (m *NhanVien) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NhanVien.Merge(m, src)
}
func (m *NhanVien) XXX_Size() int {
	return xxx_messageInfo_NhanVien.Size(m)
}
func (m *NhanVien) XXX_DiscardUnknown() {
	xxx_messageInfo_NhanVien.DiscardUnknown(m)
}

var xxx_messageInfo_NhanVien proto.InternalMessageInfo

func (m *NhanVien) GetDmNhanVienId() uint32 {
	if m != nil {
		return m.DmNhanVienId
	}
	return 0
}

func (m *NhanVien) GetMaNhanVien() string {
	if m != nil {
		return m.MaNhanVien
	}
	return ""
}

func (m *NhanVien) GetTenNhanVien() string {
	if m != nil {
		return m.TenNhanVien
	}
	return ""
}

func (m *NhanVien) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *NhanVien) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *NhanVien) GetPhongId() uint32 {
	if m != nil {
		return m.PhongId
	}
	return 0
}

func (m *NhanVien) GetDmChucDanhId() uint32 {
	if m != nil {
		return m.DmChucDanhId
	}
	return 0
}

func (m *NhanVien) GetDmChucVuId() uint32 {
	if m != nil {
		return m.DmChucVuId
	}
	return 0
}

func (m *NhanVien) GetSoDienThoai() string {
	if m != nil {
		return m.SoDienThoai
	}
	return ""
}

// Request data to read todo task
type ReadRequest struct {
	// Unique integer identifier of the todo task
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c946787ad119af67, []int{1}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Contains todo task data specified in by ID request
type DanhSachNhanVienResponse struct {
	NhanVien             []*NhanVien `protobuf:"bytes,1,rep,name=nhanVien,proto3" json:"nhanVien,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DanhSachNhanVienResponse) Reset()         { *m = DanhSachNhanVienResponse{} }
func (m *DanhSachNhanVienResponse) String() string { return proto.CompactTextString(m) }
func (*DanhSachNhanVienResponse) ProtoMessage()    {}
func (*DanhSachNhanVienResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c946787ad119af67, []int{2}
}

func (m *DanhSachNhanVienResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DanhSachNhanVienResponse.Unmarshal(m, b)
}
func (m *DanhSachNhanVienResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DanhSachNhanVienResponse.Marshal(b, m, deterministic)
}
func (m *DanhSachNhanVienResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DanhSachNhanVienResponse.Merge(m, src)
}
func (m *DanhSachNhanVienResponse) XXX_Size() int {
	return xxx_messageInfo_DanhSachNhanVienResponse.Size(m)
}
func (m *DanhSachNhanVienResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DanhSachNhanVienResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DanhSachNhanVienResponse proto.InternalMessageInfo

func (m *DanhSachNhanVienResponse) GetNhanVien() []*NhanVien {
	if m != nil {
		return m.NhanVien
	}
	return nil
}

type NhanVienResponse struct {
	NhanVien             *NhanVien `protobuf:"bytes,1,opt,name=nhanVien,proto3" json:"nhanVien,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NhanVienResponse) Reset()         { *m = NhanVienResponse{} }
func (m *NhanVienResponse) String() string { return proto.CompactTextString(m) }
func (*NhanVienResponse) ProtoMessage()    {}
func (*NhanVienResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c946787ad119af67, []int{3}
}

func (m *NhanVienResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NhanVienResponse.Unmarshal(m, b)
}
func (m *NhanVienResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NhanVienResponse.Marshal(b, m, deterministic)
}
func (m *NhanVienResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NhanVienResponse.Merge(m, src)
}
func (m *NhanVienResponse) XXX_Size() int {
	return xxx_messageInfo_NhanVienResponse.Size(m)
}
func (m *NhanVienResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NhanVienResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NhanVienResponse proto.InternalMessageInfo

func (m *NhanVienResponse) GetNhanVien() *NhanVien {
	if m != nil {
		return m.NhanVien
	}
	return nil
}

func init() {
	proto.RegisterType((*NhanVien)(nil), "proto.NhanVien")
	proto.RegisterType((*ReadRequest)(nil), "proto.ReadRequest")
	proto.RegisterType((*DanhSachNhanVienResponse)(nil), "proto.DanhSachNhanVienResponse")
	proto.RegisterType((*NhanVienResponse)(nil), "proto.NhanVienResponse")
}

func init() { proto.RegisterFile("processor_nhan_vien.proto", fileDescriptor_c946787ad119af67) }

var fileDescriptor_c946787ad119af67 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcd, 0x8a, 0xdb, 0x30,
	0x14, 0x85, 0xb1, 0xf3, 0xe7, 0x5c, 0x27, 0x75, 0xd1, 0xa6, 0x4e, 0x4b, 0xa9, 0x6b, 0x28, 0x04,
	0x0a, 0x59, 0xa4, 0xfb, 0x16, 0xd2, 0x40, 0xf0, 0x26, 0x0b, 0xa7, 0x64, 0xd1, 0x8d, 0x51, 0xac,
	0xdb, 0xca, 0x10, 0x4b, 0xae, 0x65, 0x07, 0xfa, 0x20, 0xf3, 0x32, 0xf3, 0x74, 0x83, 0xe4, 0x9f,
	0x84, 0x61, 0x7e, 0x56, 0xc6, 0xe7, 0x7c, 0x3a, 0xba, 0x47, 0x17, 0x16, 0x45, 0x29, 0x53, 0x54,
	0x4a, 0x96, 0x89, 0xe0, 0x54, 0x24, 0x97, 0x0c, 0xc5, 0xaa, 0x28, 0x65, 0x25, 0xc9, 0xc8, 0x7c,
	0xc2, 0x7b, 0x1b, 0x9c, 0x3d, 0xa7, 0xe2, 0x98, 0xa1, 0x20, 0x5f, 0xc0, 0x63, 0xf9, 0x95, 0x4c,
	0x32, 0xe6, 0x5b, 0x81, 0xb5, 0x9c, 0xc7, 0x33, 0x96, 0x77, 0x50, 0xc4, 0x48, 0x00, 0xb3, 0x9c,
	0x5e, 0x31, 0xdf, 0x0e, 0xac, 0xe5, 0x34, 0x86, 0x9c, 0xf6, 0x41, 0x21, 0xcc, 0x2b, 0x14, 0x37,
	0xc8, 0xc0, 0x20, 0x6e, 0x85, 0xa2, 0x67, 0x3e, 0xc0, 0xf4, 0x4f, 0x7d, 0x3e, 0x27, 0x82, 0xe6,
	0xe8, 0x0f, 0x8d, 0xef, 0x68, 0x61, 0x4f, 0x73, 0xd4, 0xe6, 0x99, 0xaa, 0xaa, 0x31, 0x47, 0x8d,
	0xa9, 0x05, 0x63, 0x2e, 0xc0, 0x29, 0xb8, 0x14, 0x7f, 0xf5, 0x7c, 0x63, 0x33, 0xdf, 0xc4, 0xfc,
	0x47, 0xac, 0x6d, 0x90, 0xf2, 0x3a, 0x4d, 0x18, 0x15, 0x5c, 0x13, 0x93, 0xae, 0xc1, 0x4f, 0x5e,
	0xa7, 0x5b, 0x2a, 0x78, 0xc4, 0xc8, 0x67, 0x98, 0x77, 0xd8, 0xa5, 0xd6, 0x90, 0x63, 0x20, 0x68,
	0xa0, 0x63, 0x1d, 0x31, 0x5d, 0x41, 0xc9, 0x84, 0xe9, 0x67, 0xa8, 0xb8, 0xa4, 0x99, 0x3f, 0x6d,
	0x2a, 0x28, 0xb9, 0xcd, 0x50, 0xfc, 0xd2, 0x52, 0xf8, 0x11, 0xdc, 0x18, 0x29, 0x8b, 0xf1, 0x5f,
	0x8d, 0xaa, 0x22, 0x6f, 0xc0, 0x6e, 0x5f, 0x6c, 0x10, 0xdb, 0x19, 0x0b, 0x77, 0xe0, 0xeb, 0xfb,
	0x0e, 0x34, 0xe5, 0x5d, 0xeb, 0x18, 0x55, 0x21, 0x85, 0x42, 0xf2, 0x15, 0x1c, 0xd1, 0x6a, 0xbe,
	0x15, 0x0c, 0x96, 0xee, 0xda, 0x6b, 0x16, 0xb3, 0xea, 0xd1, 0x1e, 0x08, 0x7f, 0xc0, 0xdb, 0x57,
	0x02, 0xac, 0x17, 0x03, 0xd6, 0x77, 0x16, 0x78, 0x9d, 0x7c, 0xc0, 0xf2, 0x92, 0xa5, 0x48, 0x36,
	0xe0, 0xee, 0xb0, 0xea, 0xd7, 0x41, 0xda, 0xd3, 0x37, 0x85, 0xde, 0x7f, 0x6a, 0xb5, 0x67, 0x5b,
	0x7c, 0x07, 0xef, 0x26, 0x63, 0xf3, 0x3f, 0x62, 0x4f, 0xe6, 0xbc, 0x7b, 0x3c, 0x59, 0x7b, 0x7e,
	0x33, 0xfc, 0x6d, 0x17, 0xa7, 0xd3, 0xd8, 0xb8, 0xdf, 0x1e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf3,
	0xb5, 0x0a, 0xff, 0xae, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NhanVienServiceClient is the client API for NhanVienService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NhanVienServiceClient interface {
	GetNhanVien(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*DanhSachNhanVienResponse, error)
	GetNhanVienById(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*NhanVienResponse, error)
}

type nhanVienServiceClient struct {
	cc *grpc.ClientConn
}

func NewNhanVienServiceClient(cc *grpc.ClientConn) NhanVienServiceClient {
	return &nhanVienServiceClient{cc}
}

func (c *nhanVienServiceClient) GetNhanVien(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*DanhSachNhanVienResponse, error) {
	out := new(DanhSachNhanVienResponse)
	err := c.cc.Invoke(ctx, "/proto.NhanVienService/GetNhanVien", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nhanVienServiceClient) GetNhanVienById(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*NhanVienResponse, error) {
	out := new(NhanVienResponse)
	err := c.cc.Invoke(ctx, "/proto.NhanVienService/GetNhanVienById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NhanVienServiceServer is the server API for NhanVienService service.
type NhanVienServiceServer interface {
	GetNhanVien(context.Context, *ReadRequest) (*DanhSachNhanVienResponse, error)
	GetNhanVienById(context.Context, *ReadRequest) (*NhanVienResponse, error)
}

// UnimplementedNhanVienServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNhanVienServiceServer struct {
}

func (*UnimplementedNhanVienServiceServer) GetNhanVien(ctx context.Context, req *ReadRequest) (*DanhSachNhanVienResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNhanVien not implemented")
}
func (*UnimplementedNhanVienServiceServer) GetNhanVienById(ctx context.Context, req *ReadRequest) (*NhanVienResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNhanVienById not implemented")
}

func RegisterNhanVienServiceServer(s *grpc.Server, srv NhanVienServiceServer) {
	s.RegisterService(&_NhanVienService_serviceDesc, srv)
}

func _NhanVienService_GetNhanVien_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NhanVienServiceServer).GetNhanVien(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NhanVienService/GetNhanVien",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NhanVienServiceServer).GetNhanVien(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NhanVienService_GetNhanVienById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NhanVienServiceServer).GetNhanVienById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NhanVienService/GetNhanVienById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NhanVienServiceServer).GetNhanVienById(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NhanVienService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NhanVienService",
	HandlerType: (*NhanVienServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNhanVien",
			Handler:    _NhanVienService_GetNhanVien_Handler,
		},
		{
			MethodName: "GetNhanVienById",
			Handler:    _NhanVienService_GetNhanVienById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "processor_nhan_vien.proto",
}
