// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NhanVien struct {
	DmNhanVienId         uint32   `protobuf:"varint,1,opt,name=dm_nhan_vien_id,json=dmNhanVienId,proto3" json:"dm_nhan_vien_id,omitempty"`
	MaNhanVien           string   `protobuf:"bytes,2,opt,name=ma_nhan_vien,json=maNhanVien,proto3" json:"ma_nhan_vien,omitempty"`
	TenNhanVien          string   `protobuf:"bytes,3,opt,name=ten_nhan_vien,json=tenNhanVien,proto3" json:"ten_nhan_vien,omitempty"`
	FullName             string   `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhongId              uint32   `protobuf:"varint,6,opt,name=phong_id,json=phongId,proto3" json:"phong_id,omitempty"`
	DmChucDanhId         uint32   `protobuf:"varint,7,opt,name=dm_chuc_danh_id,json=dmChucDanhId,proto3" json:"dm_chuc_danh_id,omitempty"`
	DmChucVuId           uint32   `protobuf:"varint,8,opt,name=dm_chuc_vu_id,json=dmChucVuId,proto3" json:"dm_chuc_vu_id,omitempty"`
	SoDienThoai          string   `protobuf:"bytes,9,opt,name=so_dien_thoai,json=soDienThoai,proto3" json:"so_dien_thoai,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NhanVien) Reset()         { *m = NhanVien{} }
func (m *NhanVien) String() string { return proto.CompactTextString(m) }
func (*NhanVien) ProtoMessage()    {}
func (*NhanVien) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{0}
}

func (m *NhanVien) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NhanVien.Unmarshal(m, b)
}
func (m *NhanVien) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NhanVien.Marshal(b, m, deterministic)
}
func (m *NhanVien) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NhanVien.Merge(m, src)
}
func (m *NhanVien) XXX_Size() int {
	return xxx_messageInfo_NhanVien.Size(m)
}
func (m *NhanVien) XXX_DiscardUnknown() {
	xxx_messageInfo_NhanVien.DiscardUnknown(m)
}

var xxx_messageInfo_NhanVien proto.InternalMessageInfo

func (m *NhanVien) GetDmNhanVienId() uint32 {
	if m != nil {
		return m.DmNhanVienId
	}
	return 0
}

func (m *NhanVien) GetMaNhanVien() string {
	if m != nil {
		return m.MaNhanVien
	}
	return ""
}

func (m *NhanVien) GetTenNhanVien() string {
	if m != nil {
		return m.TenNhanVien
	}
	return ""
}

func (m *NhanVien) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *NhanVien) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *NhanVien) GetPhongId() uint32 {
	if m != nil {
		return m.PhongId
	}
	return 0
}

func (m *NhanVien) GetDmChucDanhId() uint32 {
	if m != nil {
		return m.DmChucDanhId
	}
	return 0
}

func (m *NhanVien) GetDmChucVuId() uint32 {
	if m != nil {
		return m.DmChucVuId
	}
	return 0
}

func (m *NhanVien) GetSoDienThoai() string {
	if m != nil {
		return m.SoDienThoai
	}
	return ""
}

type ReadRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{1}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PhongBanNhanVienRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PhongBanId           int64    `protobuf:"varint,2,opt,name=PhongBanId,proto3" json:"PhongBanId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhongBanNhanVienRequest) Reset()         { *m = PhongBanNhanVienRequest{} }
func (m *PhongBanNhanVienRequest) String() string { return proto.CompactTextString(m) }
func (*PhongBanNhanVienRequest) ProtoMessage()    {}
func (*PhongBanNhanVienRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{2}
}

func (m *PhongBanNhanVienRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhongBanNhanVienRequest.Unmarshal(m, b)
}
func (m *PhongBanNhanVienRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhongBanNhanVienRequest.Marshal(b, m, deterministic)
}
func (m *PhongBanNhanVienRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhongBanNhanVienRequest.Merge(m, src)
}
func (m *PhongBanNhanVienRequest) XXX_Size() int {
	return xxx_messageInfo_PhongBanNhanVienRequest.Size(m)
}
func (m *PhongBanNhanVienRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PhongBanNhanVienRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PhongBanNhanVienRequest proto.InternalMessageInfo

func (m *PhongBanNhanVienRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PhongBanNhanVienRequest) GetPhongBanId() int64 {
	if m != nil {
		return m.PhongBanId
	}
	return 0
}

type DanhSachNhanVienResponse struct {
	NhanVien             []*NhanVien `protobuf:"bytes,1,rep,name=nhanVien,proto3" json:"nhanVien,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DanhSachNhanVienResponse) Reset()         { *m = DanhSachNhanVienResponse{} }
func (m *DanhSachNhanVienResponse) String() string { return proto.CompactTextString(m) }
func (*DanhSachNhanVienResponse) ProtoMessage()    {}
func (*DanhSachNhanVienResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{3}
}

func (m *DanhSachNhanVienResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DanhSachNhanVienResponse.Unmarshal(m, b)
}
func (m *DanhSachNhanVienResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DanhSachNhanVienResponse.Marshal(b, m, deterministic)
}
func (m *DanhSachNhanVienResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DanhSachNhanVienResponse.Merge(m, src)
}
func (m *DanhSachNhanVienResponse) XXX_Size() int {
	return xxx_messageInfo_DanhSachNhanVienResponse.Size(m)
}
func (m *DanhSachNhanVienResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DanhSachNhanVienResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DanhSachNhanVienResponse proto.InternalMessageInfo

func (m *DanhSachNhanVienResponse) GetNhanVien() []*NhanVien {
	if m != nil {
		return m.NhanVien
	}
	return nil
}

type NhanVienResponse struct {
	NhanVien             *NhanVien `protobuf:"bytes,1,opt,name=nhanVien,proto3" json:"nhanVien,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NhanVienResponse) Reset()         { *m = NhanVienResponse{} }
func (m *NhanVienResponse) String() string { return proto.CompactTextString(m) }
func (*NhanVienResponse) ProtoMessage()    {}
func (*NhanVienResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{4}
}

func (m *NhanVienResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NhanVienResponse.Unmarshal(m, b)
}
func (m *NhanVienResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NhanVienResponse.Marshal(b, m, deterministic)
}
func (m *NhanVienResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NhanVienResponse.Merge(m, src)
}
func (m *NhanVienResponse) XXX_Size() int {
	return xxx_messageInfo_NhanVienResponse.Size(m)
}
func (m *NhanVienResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NhanVienResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NhanVienResponse proto.InternalMessageInfo

func (m *NhanVienResponse) GetNhanVien() *NhanVien {
	if m != nil {
		return m.NhanVien
	}
	return nil
}

type PingResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{5}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*NhanVien)(nil), "proto.NhanVien")
	proto.RegisterType((*ReadRequest)(nil), "proto.ReadRequest")
	proto.RegisterType((*PhongBanNhanVienRequest)(nil), "proto.PhongBanNhanVienRequest")
	proto.RegisterType((*DanhSachNhanVienResponse)(nil), "proto.DanhSachNhanVienResponse")
	proto.RegisterType((*NhanVienResponse)(nil), "proto.NhanVienResponse")
	proto.RegisterType((*PingResponse)(nil), "proto.PingResponse")
}

func init() {
	proto.RegisterFile("user_service.proto", fileDescriptor_292f630cd9eb4c90)
}

var fileDescriptor_292f630cd9eb4c90 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x51, 0x6b, 0xdb, 0x30,
	0x14, 0x85, 0xb1, 0x93, 0x36, 0xce, 0x4d, 0xb2, 0x0c, 0xf5, 0xa1, 0xde, 0xc6, 0xba, 0xcc, 0x30,
	0x08, 0x0c, 0x3a, 0xe8, 0xde, 0x37, 0xc8, 0x0a, 0xc1, 0x7b, 0x28, 0xc5, 0xdd, 0xf2, 0xb0, 0x17,
	0xa3, 0x5a, 0x77, 0x91, 0x20, 0x96, 0x3d, 0x4b, 0x0e, 0xec, 0xef, 0xec, 0x67, 0xec, 0xd7, 0x0d,
	0xc9, 0x96, 0x6b, 0x42, 0xb3, 0x3e, 0x05, 0x9d, 0xfb, 0xe9, 0xe6, 0x9c, 0x23, 0x03, 0xa9, 0x15,
	0x56, 0xa9, 0xc2, 0x6a, 0x2f, 0x32, 0xbc, 0x2c, 0xab, 0x42, 0x17, 0xe4, 0xc4, 0xfe, 0x44, 0x7f,
	0x7d, 0x08, 0x6e, 0x38, 0x95, 0x1b, 0x81, 0x92, 0xbc, 0x83, 0x39, 0xcb, 0x53, 0xc9, 0xa9, 0x4c,
	0xf7, 0x02, 0x65, 0x2a, 0x58, 0xe8, 0x2d, 0xbc, 0xe5, 0x2c, 0x99, 0xb2, 0xdc, 0x41, 0x31, 0x23,
	0x0b, 0x98, 0xe6, 0xf4, 0x01, 0x0b, 0xfd, 0x85, 0xb7, 0x1c, 0x27, 0x90, 0xd3, 0x6e, 0x51, 0x04,
	0x33, 0x8d, 0xb2, 0x87, 0x0c, 0x2c, 0x32, 0xd1, 0x28, 0x3b, 0xe6, 0x15, 0x8c, 0x7f, 0xd6, 0xbb,
	0x5d, 0x2a, 0x69, 0x8e, 0xe1, 0xd0, 0xce, 0x03, 0x23, 0xdc, 0xd0, 0x1c, 0xcd, 0x70, 0x47, 0x95,
	0x6e, 0x86, 0x27, 0xcd, 0xd0, 0x08, 0x76, 0xf8, 0x02, 0x82, 0x92, 0x17, 0x72, 0x6b, 0xfc, 0x9d,
	0x5a, 0x7f, 0x23, 0x7b, 0x8e, 0x59, 0x9b, 0x20, 0xe3, 0x75, 0x96, 0x32, 0x2a, 0xb9, 0x21, 0x46,
	0x2e, 0xc1, 0x17, 0x5e, 0x67, 0xd7, 0x54, 0xf2, 0x98, 0x91, 0xb7, 0x30, 0x73, 0xd8, 0xbe, 0x36,
	0x50, 0x60, 0x21, 0x68, 0xa0, 0x4d, 0x1d, 0x33, 0x13, 0x41, 0x15, 0x29, 0x33, 0x35, 0x68, 0x5e,
	0x50, 0x11, 0x8e, 0x9b, 0x08, 0xaa, 0xb8, 0x16, 0x28, 0xbf, 0x19, 0x29, 0x7a, 0x0d, 0x93, 0x04,
	0x29, 0x4b, 0xf0, 0x57, 0x8d, 0x4a, 0x93, 0x67, 0xe0, 0xb7, 0x8d, 0x0d, 0x12, 0x5f, 0xb0, 0x28,
	0x86, 0xf3, 0x5b, 0xe3, 0x6b, 0x45, 0xbb, 0xd4, 0x47, 0x50, 0x72, 0x01, 0xe0, 0xd0, 0x98, 0xd9,
	0x42, 0x07, 0x49, 0x4f, 0x89, 0xd6, 0x10, 0x1a, 0xeb, 0x77, 0x34, 0xe3, 0x0f, 0xab, 0x54, 0x59,
	0x48, 0x85, 0xe4, 0x3d, 0x04, 0xb2, 0xd5, 0x42, 0x6f, 0x31, 0x58, 0x4e, 0xae, 0xe6, 0xcd, 0x1b,
	0x5f, 0x76, 0x68, 0x07, 0x44, 0x9f, 0xe1, 0xf9, 0x13, 0x0b, 0xbc, 0xff, 0x2f, 0x58, 0xc2, 0xf4,
	0x56, 0xc8, 0x6d, 0x77, 0x39, 0x84, 0x51, 0x8e, 0x4a, 0xd1, 0x2d, 0xda, 0xbb, 0xe3, 0xc4, 0x1d,
	0xaf, 0xfe, 0xf8, 0x30, 0xf9, 0xae, 0xb0, 0xba, 0x6b, 0xbe, 0x3b, 0xf2, 0x15, 0xce, 0xd6, 0xa8,
	0x0f, 0x63, 0x10, 0xd2, 0xfe, 0x57, 0xaf, 0xc9, 0x97, 0x6f, 0x5a, 0xed, 0x68, 0xe6, 0x4f, 0x30,
	0x5f, 0xa3, 0x76, 0xf2, 0xea, 0x77, 0xcc, 0x1e, 0xdd, 0x73, 0x7e, 0x98, 0xc3, 0xdd, 0xdf, 0x58,
	0x2f, 0x87, 0xaf, 0x43, 0x2e, 0x5a, 0xfe, 0xc8, 0xb3, 0x3d, 0xed, 0xeb, 0x03, 0x0c, 0x4d, 0x3b,
	0x8f, 0x9a, 0x39, 0x73, 0xcb, 0x7b, 0xf5, 0xad, 0x86, 0x3f, 0xfc, 0xf2, 0xfe, 0xfe, 0xd4, 0x4e,
	0x3e, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x68, 0x02, 0x58, 0xc1, 0xa9, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetDanhSachNhanVien(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*DanhSachNhanVienResponse, error)
	GetNhanVienById(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*NhanVienResponse, error)
	GetPhongBanNhanVien(ctx context.Context, in *PhongBanNhanVienRequest, opts ...grpc.CallOption) (*DanhSachNhanVienResponse, error)
	Ping(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetDanhSachNhanVien(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*DanhSachNhanVienResponse, error) {
	out := new(DanhSachNhanVienResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/GetDanhSachNhanVien", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetNhanVienById(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*NhanVienResponse, error) {
	out := new(NhanVienResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/GetNhanVienById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetPhongBanNhanVien(ctx context.Context, in *PhongBanNhanVienRequest, opts ...grpc.CallOption) (*DanhSachNhanVienResponse, error) {
	out := new(DanhSachNhanVienResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/GetPhongBanNhanVien", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Ping(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetDanhSachNhanVien(context.Context, *ReadRequest) (*DanhSachNhanVienResponse, error)
	GetNhanVienById(context.Context, *ReadRequest) (*NhanVienResponse, error)
	GetPhongBanNhanVien(context.Context, *PhongBanNhanVienRequest) (*DanhSachNhanVienResponse, error)
	Ping(context.Context, *ReadRequest) (*PingResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) GetDanhSachNhanVien(ctx context.Context, req *ReadRequest) (*DanhSachNhanVienResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDanhSachNhanVien not implemented")
}
func (*UnimplementedUserServiceServer) GetNhanVienById(ctx context.Context, req *ReadRequest) (*NhanVienResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNhanVienById not implemented")
}
func (*UnimplementedUserServiceServer) GetPhongBanNhanVien(ctx context.Context, req *PhongBanNhanVienRequest) (*DanhSachNhanVienResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPhongBanNhanVien not implemented")
}
func (*UnimplementedUserServiceServer) Ping(ctx context.Context, req *ReadRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetDanhSachNhanVien_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetDanhSachNhanVien(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/GetDanhSachNhanVien",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetDanhSachNhanVien(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetNhanVienById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetNhanVienById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/GetNhanVienById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetNhanVienById(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetPhongBanNhanVien_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhongBanNhanVienRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPhongBanNhanVien(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/GetPhongBanNhanVien",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPhongBanNhanVien(ctx, req.(*PhongBanNhanVienRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Ping(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDanhSachNhanVien",
			Handler:    _UserService_GetDanhSachNhanVien_Handler,
		},
		{
			MethodName: "GetNhanVienById",
			Handler:    _UserService_GetNhanVienById_Handler,
		},
		{
			MethodName: "GetPhongBanNhanVien",
			Handler:    _UserService_GetPhongBanNhanVien_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _UserService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_service.proto",
}
